struct Adjustment{
    long long TimeStamp;
    long ALabID;
    float AValue;
};

struct Temperature{
    long long TimeStamp;
    long TSensorID;
    long TLabID;
    float TValue;
};

struct Entry{
    long long TimeStamp;
    long ECalendarID;
    long ELabID;
    float EValue;
};

struct EnvironmentTemperature{
    long long TimeStamp;
    float TValue;
};

struct SystemState {
    long long TimeStamp;
    long SState; 
};

struct SystemMessage {
    long long TimeStamp;
    string SMessage;
};
